version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: urnlabs-postgres
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-urnlabs_dev}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-urnlabs_dev}"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - dependencies

  redis:
    image: redis:7-alpine
    container_name: urnlabs-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - dependencies

networks:
  dependencies:
    name: urnlabs-dependencies

volumes:
  postgres_data:
  redis_data:
