import { z } from 'zod';
export declare const WorkflowStatusSchema: z.ZodEnum<["pending", "running", "paused", "completed", "failed", "cancelled"]>;
export declare const WorkflowStepTypeSchema: z.ZodEnum<["agent_task", "condition", "parallel", "sequential", "approval", "webhook", "delay"]>;
export declare const WorkflowStepSchema: z.ZodObject<{
    id: z.ZodString;
    name: z.ZodString;
    type: z.ZodEnum<["agent_task", "condition", "parallel", "sequential", "approval", "webhook", "delay"]>;
    description: z.ZodOptional<z.ZodString>;
    agentId: z.ZodOptional<z.ZodString>;
    taskType: z.ZodOptional<z.ZodString>;
    payload: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodAny>>;
    condition: z.ZodOptional<z.ZodString>;
    timeout: z.ZodDefault<z.ZodNumber>;
    retryAttempts: z.ZodDefault<z.ZodNumber>;
    onSuccess: z.ZodOptional<z.ZodString>;
    onFailure: z.ZodOptional<z.ZodString>;
    requiresApproval: z.ZodDefault<z.ZodBoolean>;
    approvers: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    governanceChecks: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    dependencies: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    metadata: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodAny>>;
}, "strip", z.ZodTypeAny, {
    timeout: number;
    metadata: Record<string, any>;
    type: "delay" | "agent_task" | "condition" | "parallel" | "sequential" | "approval" | "webhook";
    id: string;
    name: string;
    retryAttempts: number;
    dependencies: string[];
    governanceChecks: string[];
    requiresApproval: boolean;
    approvers: string[];
    description?: string | undefined;
    agentId?: string | undefined;
    payload?: Record<string, any> | undefined;
    taskType?: string | undefined;
    condition?: string | undefined;
    onSuccess?: string | undefined;
    onFailure?: string | undefined;
}, {
    type: "delay" | "agent_task" | "condition" | "parallel" | "sequential" | "approval" | "webhook";
    id: string;
    name: string;
    timeout?: number | undefined;
    description?: string | undefined;
    metadata?: Record<string, any> | undefined;
    agentId?: string | undefined;
    payload?: Record<string, any> | undefined;
    retryAttempts?: number | undefined;
    dependencies?: string[] | undefined;
    governanceChecks?: string[] | undefined;
    taskType?: string | undefined;
    condition?: string | undefined;
    onSuccess?: string | undefined;
    onFailure?: string | undefined;
    requiresApproval?: boolean | undefined;
    approvers?: string[] | undefined;
}>;
export declare const WorkflowDefinitionSchema: z.ZodObject<{
    id: z.ZodString;
    name: z.ZodString;
    description: z.ZodString;
    version: z.ZodString;
    category: z.ZodString;
    tags: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    steps: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        name: z.ZodString;
        type: z.ZodEnum<["agent_task", "condition", "parallel", "sequential", "approval", "webhook", "delay"]>;
        description: z.ZodOptional<z.ZodString>;
        agentId: z.ZodOptional<z.ZodString>;
        taskType: z.ZodOptional<z.ZodString>;
        payload: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodAny>>;
        condition: z.ZodOptional<z.ZodString>;
        timeout: z.ZodDefault<z.ZodNumber>;
        retryAttempts: z.ZodDefault<z.ZodNumber>;
        onSuccess: z.ZodOptional<z.ZodString>;
        onFailure: z.ZodOptional<z.ZodString>;
        requiresApproval: z.ZodDefault<z.ZodBoolean>;
        approvers: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
        governanceChecks: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
        dependencies: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
        metadata: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodAny>>;
    }, "strip", z.ZodTypeAny, {
        timeout: number;
        metadata: Record<string, any>;
        type: "delay" | "agent_task" | "condition" | "parallel" | "sequential" | "approval" | "webhook";
        id: string;
        name: string;
        retryAttempts: number;
        dependencies: string[];
        governanceChecks: string[];
        requiresApproval: boolean;
        approvers: string[];
        description?: string | undefined;
        agentId?: string | undefined;
        payload?: Record<string, any> | undefined;
        taskType?: string | undefined;
        condition?: string | undefined;
        onSuccess?: string | undefined;
        onFailure?: string | undefined;
    }, {
        type: "delay" | "agent_task" | "condition" | "parallel" | "sequential" | "approval" | "webhook";
        id: string;
        name: string;
        timeout?: number | undefined;
        description?: string | undefined;
        metadata?: Record<string, any> | undefined;
        agentId?: string | undefined;
        payload?: Record<string, any> | undefined;
        retryAttempts?: number | undefined;
        dependencies?: string[] | undefined;
        governanceChecks?: string[] | undefined;
        taskType?: string | undefined;
        condition?: string | undefined;
        onSuccess?: string | undefined;
        onFailure?: string | undefined;
        requiresApproval?: boolean | undefined;
        approvers?: string[] | undefined;
    }>, "many">;
    startStep: z.ZodString;
    endSteps: z.ZodArray<z.ZodString, "many">;
    maxExecutionTime: z.ZodDefault<z.ZodNumber>;
    maxRetries: z.ZodDefault<z.ZodNumber>;
    governanceLevel: z.ZodDefault<z.ZodEnum<["basic", "standard", "strict"]>>;
    requiresApproval: z.ZodDefault<z.ZodBoolean>;
    approvers: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    permissions: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    triggers: z.ZodDefault<z.ZodArray<z.ZodObject<{
        type: z.ZodString;
        condition: z.ZodString;
        enabled: z.ZodBoolean;
    }, "strip", z.ZodTypeAny, {
        type: string;
        enabled: boolean;
        condition: string;
    }, {
        type: string;
        enabled: boolean;
        condition: string;
    }>, "many">>;
    rollbackStrategy: z.ZodDefault<z.ZodEnum<["none", "automatic", "manual"]>>;
    createdBy: z.ZodString;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
    enabled: z.ZodDefault<z.ZodBoolean>;
}, "strip", z.ZodTypeAny, {
    version: string;
    tags: string[];
    description: string;
    id: string;
    name: string;
    createdAt: Date;
    updatedAt: Date;
    steps: {
        timeout: number;
        metadata: Record<string, any>;
        type: "delay" | "agent_task" | "condition" | "parallel" | "sequential" | "approval" | "webhook";
        id: string;
        name: string;
        retryAttempts: number;
        dependencies: string[];
        governanceChecks: string[];
        requiresApproval: boolean;
        approvers: string[];
        description?: string | undefined;
        agentId?: string | undefined;
        payload?: Record<string, any> | undefined;
        taskType?: string | undefined;
        condition?: string | undefined;
        onSuccess?: string | undefined;
        onFailure?: string | undefined;
    }[];
    permissions: string[];
    enabled: boolean;
    governanceLevel: "basic" | "standard" | "strict";
    category: string;
    requiresApproval: boolean;
    approvers: string[];
    startStep: string;
    endSteps: string[];
    maxExecutionTime: number;
    maxRetries: number;
    triggers: {
        type: string;
        enabled: boolean;
        condition: string;
    }[];
    rollbackStrategy: "none" | "automatic" | "manual";
    createdBy: string;
}, {
    version: string;
    description: string;
    id: string;
    name: string;
    createdAt: Date;
    updatedAt: Date;
    steps: {
        type: "delay" | "agent_task" | "condition" | "parallel" | "sequential" | "approval" | "webhook";
        id: string;
        name: string;
        timeout?: number | undefined;
        description?: string | undefined;
        metadata?: Record<string, any> | undefined;
        agentId?: string | undefined;
        payload?: Record<string, any> | undefined;
        retryAttempts?: number | undefined;
        dependencies?: string[] | undefined;
        governanceChecks?: string[] | undefined;
        taskType?: string | undefined;
        condition?: string | undefined;
        onSuccess?: string | undefined;
        onFailure?: string | undefined;
        requiresApproval?: boolean | undefined;
        approvers?: string[] | undefined;
    }[];
    category: string;
    startStep: string;
    endSteps: string[];
    createdBy: string;
    tags?: string[] | undefined;
    permissions?: string[] | undefined;
    enabled?: boolean | undefined;
    governanceLevel?: "basic" | "standard" | "strict" | undefined;
    requiresApproval?: boolean | undefined;
    approvers?: string[] | undefined;
    maxExecutionTime?: number | undefined;
    maxRetries?: number | undefined;
    triggers?: {
        type: string;
        enabled: boolean;
        condition: string;
    }[] | undefined;
    rollbackStrategy?: "none" | "automatic" | "manual" | undefined;
}>;
export declare const WorkflowExecutionSchema: z.ZodObject<{
    id: z.ZodString;
    workflowId: z.ZodString;
    workflowVersion: z.ZodString;
    status: z.ZodEnum<["pending", "running", "paused", "completed", "failed", "cancelled"]>;
    currentStep: z.ZodOptional<z.ZodString>;
    input: z.ZodRecord<z.ZodString, z.ZodAny>;
    output: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodAny>>;
    context: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodAny>>;
    startTime: z.ZodDate;
    endTime: z.ZodOptional<z.ZodDate>;
    executionTime: z.ZodOptional<z.ZodNumber>;
    error: z.ZodOptional<z.ZodString>;
    stepExecutions: z.ZodDefault<z.ZodArray<z.ZodObject<{
        stepId: z.ZodString;
        status: z.ZodEnum<["pending", "running", "completed", "failed", "skipped"]>;
        startTime: z.ZodDate;
        endTime: z.ZodOptional<z.ZodDate>;
        input: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodAny>>;
        output: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodAny>>;
        error: z.ZodOptional<z.ZodString>;
        retryCount: z.ZodDefault<z.ZodNumber>;
        agentResponse: z.ZodOptional<z.ZodAny>;
        metadata: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodAny>>;
    }, "strip", z.ZodTypeAny, {
        metadata: Record<string, any>;
        status: "completed" | "pending" | "running" | "failed" | "skipped";
        startTime: Date;
        stepId: string;
        retryCount: number;
        error?: string | undefined;
        output?: Record<string, any> | undefined;
        input?: Record<string, any> | undefined;
        endTime?: Date | undefined;
        agentResponse?: any;
    }, {
        status: "completed" | "pending" | "running" | "failed" | "skipped";
        startTime: Date;
        stepId: string;
        error?: string | undefined;
        output?: Record<string, any> | undefined;
        metadata?: Record<string, any> | undefined;
        input?: Record<string, any> | undefined;
        endTime?: Date | undefined;
        retryCount?: number | undefined;
        agentResponse?: any;
    }>, "many">>;
    approvals: z.ZodDefault<z.ZodArray<z.ZodObject<{
        stepId: z.ZodString;
        approver: z.ZodString;
        status: z.ZodEnum<["pending", "approved", "rejected"]>;
        timestamp: z.ZodDate;
        comments: z.ZodOptional<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        status: "pending" | "rejected" | "approved";
        timestamp: Date;
        stepId: string;
        approver: string;
        comments?: string | undefined;
    }, {
        status: "pending" | "rejected" | "approved";
        timestamp: Date;
        stepId: string;
        approver: string;
        comments?: string | undefined;
    }>, "many">>;
    auditTrail: z.ZodDefault<z.ZodArray<z.ZodObject<{
        timestamp: z.ZodDate;
        action: z.ZodString;
        actor: z.ZodString;
        details: z.ZodRecord<z.ZodString, z.ZodAny>;
    }, "strip", z.ZodTypeAny, {
        timestamp: Date;
        details: Record<string, any>;
        actor: string;
        action: string;
    }, {
        timestamp: Date;
        details: Record<string, any>;
        actor: string;
        action: string;
    }>, "many">>;
    metrics: z.ZodObject<{
        totalSteps: z.ZodNumber;
        completedSteps: z.ZodNumber;
        failedSteps: z.ZodNumber;
        skippedSteps: z.ZodNumber;
        averageStepTime: z.ZodNumber;
        resourceUsage: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodNumber>>;
        qualityScore: z.ZodOptional<z.ZodNumber>;
        complianceScore: z.ZodOptional<z.ZodNumber>;
    }, "strip", z.ZodTypeAny, {
        resourceUsage: Record<string, number>;
        totalSteps: number;
        completedSteps: number;
        failedSteps: number;
        skippedSteps: number;
        averageStepTime: number;
        qualityScore?: number | undefined;
        complianceScore?: number | undefined;
    }, {
        totalSteps: number;
        completedSteps: number;
        failedSteps: number;
        skippedSteps: number;
        averageStepTime: number;
        resourceUsage?: Record<string, number> | undefined;
        qualityScore?: number | undefined;
        complianceScore?: number | undefined;
    }>;
    triggeredBy: z.ZodObject<{
        type: z.ZodString;
        user: z.ZodOptional<z.ZodString>;
        system: z.ZodOptional<z.ZodString>;
        event: z.ZodOptional<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        type: string;
        user?: string | undefined;
        system?: string | undefined;
        event?: string | undefined;
    }, {
        type: string;
        user?: string | undefined;
        system?: string | undefined;
        event?: string | undefined;
    }>;
    priority: z.ZodDefault<z.ZodEnum<["low", "medium", "high", "critical"]>>;
    tags: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
}, "strip", z.ZodTypeAny, {
    tags: string[];
    status: "completed" | "pending" | "cancelled" | "running" | "failed" | "paused";
    workflowId: string;
    id: string;
    priority: "medium" | "low" | "high" | "critical";
    input: Record<string, any>;
    context: Record<string, any>;
    auditTrail: {
        timestamp: Date;
        details: Record<string, any>;
        actor: string;
        action: string;
    }[];
    metrics: {
        resourceUsage: Record<string, number>;
        totalSteps: number;
        completedSteps: number;
        failedSteps: number;
        skippedSteps: number;
        averageStepTime: number;
        qualityScore?: number | undefined;
        complianceScore?: number | undefined;
    };
    workflowVersion: string;
    startTime: Date;
    stepExecutions: {
        metadata: Record<string, any>;
        status: "completed" | "pending" | "running" | "failed" | "skipped";
        startTime: Date;
        stepId: string;
        retryCount: number;
        error?: string | undefined;
        output?: Record<string, any> | undefined;
        input?: Record<string, any> | undefined;
        endTime?: Date | undefined;
        agentResponse?: any;
    }[];
    approvals: {
        status: "pending" | "rejected" | "approved";
        timestamp: Date;
        stepId: string;
        approver: string;
        comments?: string | undefined;
    }[];
    triggeredBy: {
        type: string;
        user?: string | undefined;
        system?: string | undefined;
        event?: string | undefined;
    };
    error?: string | undefined;
    output?: Record<string, any> | undefined;
    executionTime?: number | undefined;
    currentStep?: string | undefined;
    endTime?: Date | undefined;
}, {
    status: "completed" | "pending" | "cancelled" | "running" | "failed" | "paused";
    workflowId: string;
    id: string;
    input: Record<string, any>;
    metrics: {
        totalSteps: number;
        completedSteps: number;
        failedSteps: number;
        skippedSteps: number;
        averageStepTime: number;
        resourceUsage?: Record<string, number> | undefined;
        qualityScore?: number | undefined;
        complianceScore?: number | undefined;
    };
    workflowVersion: string;
    startTime: Date;
    triggeredBy: {
        type: string;
        user?: string | undefined;
        system?: string | undefined;
        event?: string | undefined;
    };
    error?: string | undefined;
    output?: Record<string, any> | undefined;
    tags?: string[] | undefined;
    executionTime?: number | undefined;
    priority?: "medium" | "low" | "high" | "critical" | undefined;
    context?: Record<string, any> | undefined;
    auditTrail?: {
        timestamp: Date;
        details: Record<string, any>;
        actor: string;
        action: string;
    }[] | undefined;
    currentStep?: string | undefined;
    endTime?: Date | undefined;
    stepExecutions?: {
        status: "completed" | "pending" | "running" | "failed" | "skipped";
        startTime: Date;
        stepId: string;
        error?: string | undefined;
        output?: Record<string, any> | undefined;
        metadata?: Record<string, any> | undefined;
        input?: Record<string, any> | undefined;
        endTime?: Date | undefined;
        retryCount?: number | undefined;
        agentResponse?: any;
    }[] | undefined;
    approvals?: {
        status: "pending" | "rejected" | "approved";
        timestamp: Date;
        stepId: string;
        approver: string;
        comments?: string | undefined;
    }[] | undefined;
}>;
export type WorkflowStatus = z.infer<typeof WorkflowStatusSchema>;
export type WorkflowStepType = z.infer<typeof WorkflowStepTypeSchema>;
export type WorkflowStep = z.infer<typeof WorkflowStepSchema>;
export type WorkflowDefinition = z.infer<typeof WorkflowDefinitionSchema>;
export type WorkflowExecution = z.infer<typeof WorkflowExecutionSchema>;
export interface WorkflowEngine {
    createWorkflow(definition: WorkflowDefinition): Promise<void>;
    updateWorkflow(id: string, definition: Partial<WorkflowDefinition>): Promise<void>;
    deleteWorkflow(id: string): Promise<void>;
    getWorkflow(id: string): Promise<WorkflowDefinition | null>;
    listWorkflows(filters?: Partial<WorkflowDefinition>): Promise<WorkflowDefinition[]>;
    executeWorkflow(workflowId: string, input: Record<string, any>, options?: {
        priority?: 'low' | 'medium' | 'high' | 'critical';
        triggeredBy?: {
            type: string;
            user?: string;
            system?: string;
            event?: string;
        };
        tags?: string[];
    }): Promise<string>;
    pauseExecution(executionId: string): Promise<void>;
    resumeExecution(executionId: string): Promise<void>;
    cancelExecution(executionId: string, reason?: string): Promise<void>;
    getExecution(executionId: string): Promise<WorkflowExecution | null>;
    listExecutions(filters?: {
        workflowId?: string;
        status?: WorkflowStatus;
        startDate?: Date;
        endDate?: Date;
    }): Promise<WorkflowExecution[]>;
    approveStep(executionId: string, stepId: string, approver: string, comments?: string): Promise<void>;
    rejectStep(executionId: string, stepId: string, approver: string, reason: string): Promise<void>;
    getPendingApprovals(approver?: string): Promise<Array<{
        executionId: string;
        stepId: string;
        workflowName: string;
        requestedAt: Date;
    }>>;
}
export declare const WorkflowEventSchema: z.ZodObject<{
    id: z.ZodString;
    executionId: z.ZodString;
    workflowId: z.ZodString;
    type: z.ZodEnum<["workflow_started", "workflow_completed", "workflow_failed", "workflow_paused", "workflow_resumed", "workflow_cancelled", "step_started", "step_completed", "step_failed", "approval_requested", "approval_granted", "approval_rejected"]>;
    timestamp: z.ZodDate;
    data: z.ZodRecord<z.ZodString, z.ZodAny>;
    severity: z.ZodEnum<["info", "warning", "error", "critical"]>;
}, "strip", z.ZodTypeAny, {
    type: "workflow_completed" | "workflow_failed" | "approval_requested" | "approval_granted" | "approval_rejected" | "workflow_started" | "workflow_paused" | "workflow_resumed" | "workflow_cancelled" | "step_started" | "step_completed" | "step_failed";
    timestamp: Date;
    workflowId: string;
    severity: "error" | "info" | "warning" | "critical";
    id: string;
    data: Record<string, any>;
    executionId: string;
}, {
    type: "workflow_completed" | "workflow_failed" | "approval_requested" | "approval_granted" | "approval_rejected" | "workflow_started" | "workflow_paused" | "workflow_resumed" | "workflow_cancelled" | "step_started" | "step_completed" | "step_failed";
    timestamp: Date;
    workflowId: string;
    severity: "error" | "info" | "warning" | "critical";
    id: string;
    data: Record<string, any>;
    executionId: string;
}>;
export type WorkflowEvent = z.infer<typeof WorkflowEventSchema>;
export declare const WorkflowTemplateSchema: z.ZodObject<{
    id: z.ZodString;
    name: z.ZodString;
    description: z.ZodString;
    category: z.ZodString;
    tags: z.ZodArray<z.ZodString, "many">;
    template: z.ZodObject<Omit<{
        id: z.ZodString;
        name: z.ZodString;
        description: z.ZodString;
        version: z.ZodString;
        category: z.ZodString;
        tags: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
        steps: z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            name: z.ZodString;
            type: z.ZodEnum<["agent_task", "condition", "parallel", "sequential", "approval", "webhook", "delay"]>;
            description: z.ZodOptional<z.ZodString>;
            agentId: z.ZodOptional<z.ZodString>;
            taskType: z.ZodOptional<z.ZodString>;
            payload: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodAny>>;
            condition: z.ZodOptional<z.ZodString>;
            timeout: z.ZodDefault<z.ZodNumber>;
            retryAttempts: z.ZodDefault<z.ZodNumber>;
            onSuccess: z.ZodOptional<z.ZodString>;
            onFailure: z.ZodOptional<z.ZodString>;
            requiresApproval: z.ZodDefault<z.ZodBoolean>;
            approvers: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
            governanceChecks: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
            dependencies: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
            metadata: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodAny>>;
        }, "strip", z.ZodTypeAny, {
            timeout: number;
            metadata: Record<string, any>;
            type: "delay" | "agent_task" | "condition" | "parallel" | "sequential" | "approval" | "webhook";
            id: string;
            name: string;
            retryAttempts: number;
            dependencies: string[];
            governanceChecks: string[];
            requiresApproval: boolean;
            approvers: string[];
            description?: string | undefined;
            agentId?: string | undefined;
            payload?: Record<string, any> | undefined;
            taskType?: string | undefined;
            condition?: string | undefined;
            onSuccess?: string | undefined;
            onFailure?: string | undefined;
        }, {
            type: "delay" | "agent_task" | "condition" | "parallel" | "sequential" | "approval" | "webhook";
            id: string;
            name: string;
            timeout?: number | undefined;
            description?: string | undefined;
            metadata?: Record<string, any> | undefined;
            agentId?: string | undefined;
            payload?: Record<string, any> | undefined;
            retryAttempts?: number | undefined;
            dependencies?: string[] | undefined;
            governanceChecks?: string[] | undefined;
            taskType?: string | undefined;
            condition?: string | undefined;
            onSuccess?: string | undefined;
            onFailure?: string | undefined;
            requiresApproval?: boolean | undefined;
            approvers?: string[] | undefined;
        }>, "many">;
        startStep: z.ZodString;
        endSteps: z.ZodArray<z.ZodString, "many">;
        maxExecutionTime: z.ZodDefault<z.ZodNumber>;
        maxRetries: z.ZodDefault<z.ZodNumber>;
        governanceLevel: z.ZodDefault<z.ZodEnum<["basic", "standard", "strict"]>>;
        requiresApproval: z.ZodDefault<z.ZodBoolean>;
        approvers: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
        permissions: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
        triggers: z.ZodDefault<z.ZodArray<z.ZodObject<{
            type: z.ZodString;
            condition: z.ZodString;
            enabled: z.ZodBoolean;
        }, "strip", z.ZodTypeAny, {
            type: string;
            enabled: boolean;
            condition: string;
        }, {
            type: string;
            enabled: boolean;
            condition: string;
        }>, "many">>;
        rollbackStrategy: z.ZodDefault<z.ZodEnum<["none", "automatic", "manual"]>>;
        createdBy: z.ZodString;
        createdAt: z.ZodDate;
        updatedAt: z.ZodDate;
        enabled: z.ZodDefault<z.ZodBoolean>;
    }, "id" | "createdAt" | "updatedAt" | "createdBy">, "strip", z.ZodTypeAny, {
        version: string;
        tags: string[];
        description: string;
        name: string;
        steps: {
            timeout: number;
            metadata: Record<string, any>;
            type: "delay" | "agent_task" | "condition" | "parallel" | "sequential" | "approval" | "webhook";
            id: string;
            name: string;
            retryAttempts: number;
            dependencies: string[];
            governanceChecks: string[];
            requiresApproval: boolean;
            approvers: string[];
            description?: string | undefined;
            agentId?: string | undefined;
            payload?: Record<string, any> | undefined;
            taskType?: string | undefined;
            condition?: string | undefined;
            onSuccess?: string | undefined;
            onFailure?: string | undefined;
        }[];
        permissions: string[];
        enabled: boolean;
        governanceLevel: "basic" | "standard" | "strict";
        category: string;
        requiresApproval: boolean;
        approvers: string[];
        startStep: string;
        endSteps: string[];
        maxExecutionTime: number;
        maxRetries: number;
        triggers: {
            type: string;
            enabled: boolean;
            condition: string;
        }[];
        rollbackStrategy: "none" | "automatic" | "manual";
    }, {
        version: string;
        description: string;
        name: string;
        steps: {
            type: "delay" | "agent_task" | "condition" | "parallel" | "sequential" | "approval" | "webhook";
            id: string;
            name: string;
            timeout?: number | undefined;
            description?: string | undefined;
            metadata?: Record<string, any> | undefined;
            agentId?: string | undefined;
            payload?: Record<string, any> | undefined;
            retryAttempts?: number | undefined;
            dependencies?: string[] | undefined;
            governanceChecks?: string[] | undefined;
            taskType?: string | undefined;
            condition?: string | undefined;
            onSuccess?: string | undefined;
            onFailure?: string | undefined;
            requiresApproval?: boolean | undefined;
            approvers?: string[] | undefined;
        }[];
        category: string;
        startStep: string;
        endSteps: string[];
        tags?: string[] | undefined;
        permissions?: string[] | undefined;
        enabled?: boolean | undefined;
        governanceLevel?: "basic" | "standard" | "strict" | undefined;
        requiresApproval?: boolean | undefined;
        approvers?: string[] | undefined;
        maxExecutionTime?: number | undefined;
        maxRetries?: number | undefined;
        triggers?: {
            type: string;
            enabled: boolean;
            condition: string;
        }[] | undefined;
        rollbackStrategy?: "none" | "automatic" | "manual" | undefined;
    }>;
    parameters: z.ZodArray<z.ZodObject<{
        name: z.ZodString;
        type: z.ZodString;
        description: z.ZodString;
        required: z.ZodBoolean;
        defaultValue: z.ZodOptional<z.ZodAny>;
        validation: z.ZodOptional<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        description: string;
        type: string;
        name: string;
        required: boolean;
        validation?: string | undefined;
        defaultValue?: any;
    }, {
        description: string;
        type: string;
        name: string;
        required: boolean;
        validation?: string | undefined;
        defaultValue?: any;
    }>, "many">;
    version: z.ZodString;
    createdBy: z.ZodString;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    version: string;
    tags: string[];
    description: string;
    id: string;
    name: string;
    createdAt: Date;
    updatedAt: Date;
    parameters: {
        description: string;
        type: string;
        name: string;
        required: boolean;
        validation?: string | undefined;
        defaultValue?: any;
    }[];
    category: string;
    createdBy: string;
    template: {
        version: string;
        tags: string[];
        description: string;
        name: string;
        steps: {
            timeout: number;
            metadata: Record<string, any>;
            type: "delay" | "agent_task" | "condition" | "parallel" | "sequential" | "approval" | "webhook";
            id: string;
            name: string;
            retryAttempts: number;
            dependencies: string[];
            governanceChecks: string[];
            requiresApproval: boolean;
            approvers: string[];
            description?: string | undefined;
            agentId?: string | undefined;
            payload?: Record<string, any> | undefined;
            taskType?: string | undefined;
            condition?: string | undefined;
            onSuccess?: string | undefined;
            onFailure?: string | undefined;
        }[];
        permissions: string[];
        enabled: boolean;
        governanceLevel: "basic" | "standard" | "strict";
        category: string;
        requiresApproval: boolean;
        approvers: string[];
        startStep: string;
        endSteps: string[];
        maxExecutionTime: number;
        maxRetries: number;
        triggers: {
            type: string;
            enabled: boolean;
            condition: string;
        }[];
        rollbackStrategy: "none" | "automatic" | "manual";
    };
}, {
    version: string;
    tags: string[];
    description: string;
    id: string;
    name: string;
    createdAt: Date;
    updatedAt: Date;
    parameters: {
        description: string;
        type: string;
        name: string;
        required: boolean;
        validation?: string | undefined;
        defaultValue?: any;
    }[];
    category: string;
    createdBy: string;
    template: {
        version: string;
        description: string;
        name: string;
        steps: {
            type: "delay" | "agent_task" | "condition" | "parallel" | "sequential" | "approval" | "webhook";
            id: string;
            name: string;
            timeout?: number | undefined;
            description?: string | undefined;
            metadata?: Record<string, any> | undefined;
            agentId?: string | undefined;
            payload?: Record<string, any> | undefined;
            retryAttempts?: number | undefined;
            dependencies?: string[] | undefined;
            governanceChecks?: string[] | undefined;
            taskType?: string | undefined;
            condition?: string | undefined;
            onSuccess?: string | undefined;
            onFailure?: string | undefined;
            requiresApproval?: boolean | undefined;
            approvers?: string[] | undefined;
        }[];
        category: string;
        startStep: string;
        endSteps: string[];
        tags?: string[] | undefined;
        permissions?: string[] | undefined;
        enabled?: boolean | undefined;
        governanceLevel?: "basic" | "standard" | "strict" | undefined;
        requiresApproval?: boolean | undefined;
        approvers?: string[] | undefined;
        maxExecutionTime?: number | undefined;
        maxRetries?: number | undefined;
        triggers?: {
            type: string;
            enabled: boolean;
            condition: string;
        }[] | undefined;
        rollbackStrategy?: "none" | "automatic" | "manual" | undefined;
    };
}>;
export type WorkflowTemplate = z.infer<typeof WorkflowTemplateSchema>;
export declare const STANDARD_WORKFLOWS: {
    readonly FEATURE_DEVELOPMENT: "feature-development-v1";
    readonly CODE_REVIEW: "code-review-v1";
    readonly DEPLOYMENT: "deployment-v1";
    readonly SECURITY_AUDIT: "security-audit-v1";
    readonly PERFORMANCE_OPTIMIZATION: "performance-optimization-v1";
    readonly BUG_FIX: "bug-fix-v1";
    readonly DOCUMENTATION_UPDATE: "docs-update-v1";
};
//# sourceMappingURL=WorkflowTypes.d.ts.map