import { WAFRule } from '../types.js';

/**
 * OWASP Top 10 Protection Rules
 * Based on OWASP Top 10 2021 and Core Rule Set (CRS)
 */
export const OWASP_RULES: WAFRule[] = [
  // A01:2021 – Broken Access Control
  {
    id: 'owasp_001_broken_access_control',
    name: 'Broken Access Control Detection',
    description: 'Detects attempts to access restricted resources or bypass access controls',
    category: 'information_disclosure',
    threatLevel: 'high',
    action: 'block',
    enabled: true,
    patterns: [
      '/admin/',
      '/administrator/',
      '/.env',
      '/.git/',
      '/config/',
      '/wp-admin/',
      '/phpmyadmin/',
      '/management/',
      '/control-panel/',
      '/dashboard/',
      '/.aws/',
      '/.azure/',
      '/backup/',
      '/private/',
      '/internal/',
      '/.well-known/security.txt'
    ],
    paths: [
      '/admin/*',
      '/administrator/*',
      '/.env*',
      '/.git/*',
      '/config/*',
      '/backup/*',
      '/private/*',
      '/internal/*'
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
    tags: ['owasp', 'access-control', 'authentication']
  },

  // A02:2021 – Cryptographic Failures
  {
    id: 'owasp_002_crypto_failures',
    name: 'Cryptographic Failures Detection',
    description: 'Detects weak cryptographic implementations and data exposure',
    category: 'information_disclosure',
    threatLevel: 'high',
    action: 'block',
    enabled: true,
    patterns: [
      'password=',
      'passwd=',
      'secret=',
      'token=',
      'key=',
      'api_key=',
      'access_token=',
      'private_key=',
      'ssh_key=',
      'database_url=',
      'connection_string='
    ],
    customPattern: '(password|passwd|secret|token|key|api_key|access_token|private_key|ssh_key|database_url|connection_string)\\s*[=:]\\s*[\'"]?[\\w\\-\\.]+[\'"]?',
    createdAt: new Date(),
    updatedAt: new Date(),
    tags: ['owasp', 'cryptography', 'data-exposure']
  },

  // A03:2021 – Injection (SQL Injection)
  {
    id: 'owasp_003_sql_injection',
    name: 'SQL Injection Detection',
    description: 'Detects SQL injection attempts using common patterns and techniques',
    category: 'sql_injection',
    threatLevel: 'critical',
    action: 'block',
    enabled: true,
    patterns: [
      "' OR '1'='1",
      "' OR 1=1--",
      "' OR 1=1#",
      "'; DROP TABLE",
      "'; DELETE FROM",
      "'; INSERT INTO",
      "' UNION SELECT",
      "' AND 1=1--",
      "' AND 1=2--",
      "1' OR '1'='1",
      "1 OR 1=1",
      "admin'--",
      "admin'#",
      "' OR 'a'='a",
      "' OR 'x'='x",
      "') OR ('1'='1",
      "'; EXEC(",
      "'; SELECT",
      "benchmark(",
      "sleep(",
      "waitfor delay",
      "pg_sleep(",
      "information_schema",
      "sysobjects",
      "syscolumns",
      "msysaccessobjects"
    ],
    customPattern: "(union\\s+(all\\s+)?select|select\\s+.*\\s+from\\s+|insert\\s+into\\s+|delete\\s+from\\s+|update\\s+.*\\s+set\\s+|drop\\s+(table|database)|exec\\s*\\(|script\\s*>|'\\s*or\\s*'1'='1|'\\s*or\\s*1=1\\s*--|benchmark\\s*\\(|sleep\\s*\\(|waitfor\\s+delay)",
    createdAt: new Date(),
    updatedAt: new Date(),
    tags: ['owasp', 'injection', 'sql', 'database']
  },

  // A03:2021 – Injection (NoSQL Injection)
  {
    id: 'owasp_003_nosql_injection',
    name: 'NoSQL Injection Detection',
    description: 'Detects NoSQL injection attempts targeting MongoDB, CouchDB, etc.',
    category: 'nosql_injection',
    threatLevel: 'high',
    action: 'block',
    enabled: true,
    patterns: [
      '$where',
      '$ne',
      '$gt',
      '$lt',
      '$gte',
      '$lte',
      '$regex',
      '$exists',
      '$type',
      '$in',
      '$nin',
      '$all',
      '$size',
      '$elemMatch',
      '{"$where"',
      '{"$ne"',
      '{"$gt"',
      '{"$regex"',
      'this.password',
      'this.username',
      'function(){',
      'return true',
      'sleep(',
      'benchmark('
    ],
    customPattern: '(\\$where|\\$ne|\\$gt|\\$lt|\\$gte|\\$lte|\\$regex|\\$exists|\\$type|\\$in|\\$nin|\\$all|\\$size|\\$elemMatch|this\\.(password|username|email)|function\\s*\\(|return\\s+true)',
    createdAt: new Date(),
    updatedAt: new Date(),
    tags: ['owasp', 'injection', 'nosql', 'mongodb']
  },

  // A03:2021 – Injection (XSS)
  {
    id: 'owasp_003_xss_injection',
    name: 'Cross-Site Scripting (XSS) Detection',
    description: 'Detects reflected, stored, and DOM-based XSS attacks',
    category: 'xss',
    threatLevel: 'high',
    action: 'block',
    enabled: true,
    patterns: [
      '<script',
      '</script>',
      'javascript:',
      'vbscript:',
      'onload=',
      'onerror=',
      'onclick=',
      'onmouseover=',
      'onfocus=',
      'onblur=',
      'onchange=',
      'onsubmit=',
      'document.cookie',
      'document.write',
      'eval(',
      'setTimeout(',
      'setInterval(',
      'innerHTML=',
      'outerHTML=',
      'location.href=',
      'window.location=',
      '<iframe',
      '<object',
      '<embed',
      '<link',
      '<meta',
      'expression(',
      'url(javascript:',
      'style=',
      'background:',
      'background-image:'
    ],
    customPattern: '(<script[^>]*>.*?</script>|<iframe[^>]*>|<object[^>]*>|<embed[^>]*>|<link[^>]*>|javascript:|vbscript:|on\\w+\\s*=|expression\\s*\\(|document\\.(cookie|write)|eval\\s*\\(|setTimeout\\s*\\(|setInterval\\s*\\()',
    createdAt: new Date(),
    updatedAt: new Date(),
    tags: ['owasp', 'injection', 'xss', 'javascript']
  },

  // A03:2021 – Injection (Command Injection)
  {
    id: 'owasp_003_command_injection',
    name: 'Command Injection Detection',
    description: 'Detects OS command injection attempts',
    category: 'command_injection',
    threatLevel: 'critical',
    action: 'block',
    enabled: true,
    patterns: [
      ';rm',
      ';cat',
      ';ls',
      ';ps',
      ';kill',
      ';nc',
      ';netcat',
      ';wget',
      ';curl',
      ';ping',
      ';nslookup',
      ';dig',
      ';telnet',
      ';ssh',
      ';scp',
      ';tar',
      ';gzip',
      ';gunzip',
      ';unzip',
      ';chmod',
      ';chown',
      ';sudo',
      ';su',
      ';passwd',
      ';mount',
      ';umount',
      ';fdisk',
      ';format',
      ';del',
      ';rmdir',
      ';taskkill',
      ';net',
      ';cmd',
      ';powershell',
      ';bash',
      ';sh',
      ';zsh',
      ';fish',
      '&&',
      '||',
      '`',
      '$(',
      '${',
      '|',
      '>',
      '>>',
      '<'
    ],
    customPattern: '([;&|`$(){}\\[\\]]|\\|\\s*\\w+|;\\s*\\w+|&&\\s*\\w+|\\|\\|\\s*\\w+|`.*`|\\$\\(.*\\)|\\${.*}|nc\\s+-l|curl\\s+|wget\\s+|bash\\s+|sh\\s+|cmd\\s+|powershell\\s+|rm\\s+-rf|del\\s+)',
    createdAt: new Date(),
    updatedAt: new Date(),
    tags: ['owasp', 'injection', 'command', 'rce']
  },

  // A04:2021 – Insecure Design (Path Traversal)
  {
    id: 'owasp_004_path_traversal',
    name: 'Path Traversal Detection',
    description: 'Detects directory traversal and local file inclusion attempts',
    category: 'path_traversal',
    threatLevel: 'high',
    action: 'block',
    enabled: true,
    patterns: [
      '../',
      '..\\\\',
      '..%2f',
      '..%2F',
      '..%5c',
      '..%5C',
      '%2e%2e%2f',
      '%2e%2e%5c',
      '/etc/passwd',
      '/etc/shadow',
      '/etc/hosts',
      '/proc/version',
      '/proc/self/environ',
      '/windows/system32/',
      '/boot.ini',
      'web.config',
      '\\\\windows\\\\',
      '\\\\system32\\\\',
      'file://',
      'file:\\\\',
      'c:\\\\',
      'd:\\\\',
      'e:\\\\',
      'f:\\\\'
    ],
    customPattern: '(\\.\\./|\\.\\.\\\\\\\|\\.\\.%2f|\\.\\.%2F|\\.\\.%5c|\\.\\.%5C|%2e%2e%2f|%2e%2e%5c|/etc/(passwd|shadow|hosts)|/proc/(version|self/environ)|/windows/system32|/boot\\.ini|web\\.config|\\\\\\\\windows\\\\\\\\|file://|file:\\\\\\\\|[a-z]:\\\\\\\\)',
    createdAt: new Date(),
    updatedAt: new Date(),
    tags: ['owasp', 'path-traversal', 'lfi', 'file-inclusion']
  },

  // A05:2021 – Security Misconfiguration
  {
    id: 'owasp_005_security_misconfiguration',
    name: 'Security Misconfiguration Detection',
    description: 'Detects access to sensitive files and debug information',
    category: 'information_disclosure',
    threatLevel: 'medium',
    action: 'block',
    enabled: true,
    patterns: [
      '/.htaccess',
      '/.htpasswd',
      '/web.config',
      '/robots.txt',
      '/sitemap.xml',
      '/.DS_Store',
      '/thumbs.db',
      '/server-status',
      '/server-info',
      '/phpinfo.php',
      '/info.php',
      '/test.php',
      '/debug',
      '/trace',
      '/console',
      '/actuator/',
      '/health',
      '/metrics',
      '/swagger',
      '/api-docs',
      '/docs/',
      '/.env',
      '/.env.local',
      '/.env.production',
      '/package.json',
      '/composer.json',
      '/Gemfile',
      '/requirements.txt',
      '/yarn.lock',
      '/package-lock.json',
      '/.git/',
      '/.svn/',
      '/.hg/',
      '/.bzr/',
      '/CVS/',
      '/WEB-INF/',
      '/META-INF/',
      '/crossdomain.xml',
      '/clientaccesspolicy.xml'
    ],
    customPattern: '(/\\.htaccess|/\\.htpasswd|/web\\.config|/robots\\.txt|/\\.DS_Store|/thumbs\\.db|/server-(status|info)|/phpinfo\\.php|/info\\.php|/test\\.php|/debug|/trace|/console|/actuator/|/health|/metrics|/swagger|/api-docs|/docs/|/\\.env|/package\\.json|/composer\\.json|/Gemfile|/requirements\\.txt|/yarn\\.lock|/package-lock\\.json|/\\.git/|/\\.svn/|/\\.hg/|/\\.bzr/|/CVS/|/WEB-INF/|/META-INF/|/crossdomain\\.xml|/clientaccesspolicy\\.xml)',
    createdAt: new Date(),
    updatedAt: new Date(),
    tags: ['owasp', 'misconfiguration', 'information-disclosure']
  },

  // A06:2021 – Vulnerable and Outdated Components
  {
    id: 'owasp_006_vulnerable_components',
    name: 'Vulnerable Components Detection',
    description: 'Detects exploitation of known vulnerable components',
    category: 'information_disclosure',
    threatLevel: 'high',
    action: 'log',
    enabled: true,
    patterns: [
      '/struts2-showcase/',
      '/struts2-rest-showcase/',
      '/apache-struts',
      '/spring-boot-actuator',
      '/jolokia/',
      '/manager/html',
      '/manager/text',
      '/host-manager/',
      '/jmx-console/',
      '/web-console/',
      '/invoker/',
      '/axis/',
      '/axis2/',
      '/xmlrpc',
      '/rpc/',
      '/cgi-bin/',
      '/fcgi-bin/',
      '/servlet/',
      '/services/',
      '/wsdl',
      '?wsdl',
      '/wp-includes/',
      '/wp-content/',
      '/wp-admin/',
      '/wp-login.php',
      '/wordpress/',
      '/drupal/',
      '/joomla/',
      '/moodle/',
      '/magento/',
      '/prestashop/'
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
    tags: ['owasp', 'vulnerable-components', 'known-exploits']
  },

  // A07:2021 – Identification and Authentication Failures
  {
    id: 'owasp_007_auth_failures',
    name: 'Authentication Failures Detection',
    description: 'Detects authentication bypass and brute force attempts',
    category: 'session_fixation',
    threatLevel: 'high',
    action: 'log',
    enabled: true,
    patterns: [
      'admin/admin',
      'administrator/administrator',
      'root/root',
      'admin/password',
      'admin/123456',
      'admin/admin123',
      'test/test',
      'guest/guest',
      'user/user',
      'demo/demo',
      'sa/',
      'admin/',
      '/login.php',
      '/login.asp',
      '/login.jsp',
      '/signin',
      '/auth',
      '/authenticate',
      'password=',
      'username=',
      'login=',
      'user=',
      'pass='
    ],
    rateLimit: {
      maxRequests: 5,
      window: 300, // 5 minutes
      byIP: true
    },
    createdAt: new Date(),
    updatedAt: new Date(),
    tags: ['owasp', 'authentication', 'brute-force']
  },

  // A08:2021 – Software and Data Integrity Failures
  {
    id: 'owasp_008_integrity_failures',
    name: 'Data Integrity Failures Detection',
    description: 'Detects insecure deserialization and untrusted data processing',
    category: 'information_disclosure',
    threatLevel: 'high',
    action: 'block',
    enabled: true,
    patterns: [
      'java.lang.Runtime',
      'java.lang.ProcessBuilder',
      'java.io.FileInputStream',
      'java.io.ObjectInputStream',
      'java.net.URL',
      'javax.script.ScriptEngine',
      'org.apache.commons.collections',
      'pickle.loads',
      'cPickle.loads',
      'yaml.load',
      'eval(',
      'exec(',
      'unserialize(',
      'file_get_contents(',
      'readfile(',
      'fopen(',
      'fread(',
      'include(',
      'require(',
      'import',
      '__import__'
    ],
    customPattern: '(java\\.lang\\.(Runtime|ProcessBuilder)|java\\.io\\.(FileInputStream|ObjectInputStream)|java\\.net\\.URL|javax\\.script\\.ScriptEngine|org\\.apache\\.commons\\.collections|pickle\\.loads|cPickle\\.loads|yaml\\.load|eval\\s*\\(|exec\\s*\\(|unserialize\\s*\\(|file_get_contents\\s*\\(|readfile\\s*\\(|fopen\\s*\\(|fread\\s*\\(|include\\s*\\(|require\\s*\\(|__import__)',
    createdAt: new Date(),
    updatedAt: new Date(),
    tags: ['owasp', 'integrity', 'deserialization']
  },

  // A09:2021 – Security Logging and Monitoring Failures
  {
    id: 'owasp_009_logging_failures',
    name: 'Monitoring Evasion Detection',
    description: 'Detects attempts to evade logging and monitoring',
    category: 'information_disclosure',
    threatLevel: 'medium',
    action: 'log',
    enabled: true,
    patterns: [
      '/dev/null',
      '2>/dev/null',
      '1>/dev/null',
      '&>/dev/null',
      'nohup',
      'screen -d',
      'tmux',
      'disown',
      '>/dev/null',
      'history -c',
      'history -w',
      'unset HISTFILE',
      'export HISTSIZE=0',
      'rm ~/.bash_history',
      'shred',
      'wipe',
      'srm'
    ],
    customPattern: '(/dev/null|2>/dev/null|1>/dev/null|&>/dev/null|nohup|screen\\s+-d|tmux|disown|>/dev/null|history\\s+-[cw]|unset\\s+HISTFILE|export\\s+HISTSIZE=0|rm\\s+~/\\.bash_history|shred|wipe|srm)',
    createdAt: new Date(),
    updatedAt: new Date(),
    tags: ['owasp', 'evasion', 'anti-forensics']
  },

  // A10:2021 – Server-Side Request Forgery (SSRF)
  {
    id: 'owasp_010_ssrf',
    name: 'Server-Side Request Forgery Detection',
    description: 'Detects SSRF attempts targeting internal resources',
    category: 'ssrf',
    threatLevel: 'high',
    action: 'block',
    enabled: true,
    patterns: [
      'localhost',
      '127.0.0.1',
      '0.0.0.0',
      '10.',
      '172.16.',
      '172.17.',
      '172.18.',
      '172.19.',
      '172.20.',
      '172.21.',
      '172.22.',
      '172.23.',
      '172.24.',
      '172.25.',
      '172.26.',
      '172.27.',
      '172.28.',
      '172.29.',
      '172.30.',
      '172.31.',
      '192.168.',
      '169.254.',
      'metadata.google.internal',
      '169.254.169.254',
      'metadata.goog',
      'metadata',
      'ec2-',
      'amazonaws.com',
      'compute.internal',
      'consul',
      'vault',
      'etcd',
      'kubernetes',
      'docker',
      'gopher://',
      'dict://',
      'ftp://',
      'sftp://',
      'ldap://',
      'ldaps://',
      'tftp://',
      'file://'
    ],
    customPattern: '(localhost|127\\.0\\.0\\.1|0\\.0\\.0\\.0|10\\.|172\\.(1[6-9]|2[0-9]|3[0-1])\\.|192\\.168\\.|169\\.254\\.|metadata\\.google\\.internal|169\\.254\\.169\\.254|metadata\\.goog|ec2-|amazonaws\\.com|compute\\.internal|consul|vault|etcd|kubernetes|docker|gopher://|dict://|ftp://|sftp://|ldap://|ldaps://|tftp://|file://)',
    createdAt: new Date(),
    updatedAt: new Date(),
    tags: ['owasp', 'ssrf', 'metadata']
  },

  // Additional OWASP-related rules

  // XXE (XML External Entity) Detection
  {
    id: 'owasp_xxe_detection',
    name: 'XML External Entity (XXE) Detection',
    description: 'Detects XXE injection attempts',
    category: 'xxe',
    threatLevel: 'high',
    action: 'block',
    enabled: true,
    patterns: [
      '<!ENTITY',
      '<!DOCTYPE',
      'SYSTEM',
      'PUBLIC',
      'file://',
      'http://',
      'https://',
      'ftp://',
      'expect://',
      'php://',
      'data://',
      'zip://',
      'jar://',
      '&xxe;',
      '&file;',
      '&passwd;',
      '&etc;'
    ],
    customPattern: '(<!ENTITY|<!DOCTYPE|SYSTEM|PUBLIC|file://|http://|https://|ftp://|expect://|php://|data://|zip://|jar://|&\\w+;)',
    headers: {
      'Content-Type': 'application/xml'
    },
    createdAt: new Date(),
    updatedAt: new Date(),
    tags: ['owasp', 'xxe', 'xml']
  },

  // CSRF Detection
  {
    id: 'owasp_csrf_detection',
    name: 'Cross-Site Request Forgery Detection',
    description: 'Detects potential CSRF attacks',
    category: 'csrf',
    threatLevel: 'medium',
    action: 'log',
    enabled: true,
    methods: ['POST', 'PUT', 'DELETE', 'PATCH'],
    customPattern: '',
    createdAt: new Date(),
    updatedAt: new Date(),
    tags: ['owasp', 'csrf', 'state-changing']
  },

  // LDAP Injection Detection
  {
    id: 'owasp_ldap_injection',
    name: 'LDAP Injection Detection',
    description: 'Detects LDAP injection attempts',
    category: 'ldap_injection',
    threatLevel: 'high',
    action: 'block',
    enabled: true,
    patterns: [
      '*)(uid=*',
      '*)(cn=*',
      '*)(&(uid=*',
      '*)(|(uid=*',
      '*)(objectClass=*',
      '*))(|(uid=*',
      '*)(userPassword=*',
      '*)(mail=*',
      '*)(sn=*',
      '*)(givenName=*'
    ],
    customPattern: '(\\*\\)\\((uid|cn|objectClass|userPassword|mail|sn|givenName)=\\*|\\*\\)\\(&\\(uid=\\*|\\*\\)\\(\\|\\(uid=\\*|\\*\\)\\)\\(\\|\\(uid=\\*)',
    createdAt: new Date(),
    updatedAt: new Date(),
    tags: ['owasp', 'ldap', 'injection']
  }
];

export default OWASP_RULES;